ClimateStore.WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClimateStore.Domain.Abstract;
using ClimateStore.Domain.Entities;
using ClimateStore.WebUI.Models;

namespace ClimateStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository repository;
        private IOrderProcessor orderProcessor;
        public CartController(IProductRepository repo, IOrderProcessor proc)
        {
            repository = repo;
            orderProcessor = proc;
        }

        public ViewResult Index(Cart cart, string returnUrl)//added Cart cart to bind
        {
            return View(new CartIndexViewModel
            {
                //Cart = GetCart(),
                Cart = cart,
                ReturnUrl = returnUrl

            }
                );
        }

        public RedirectToRouteResult AddToCart(Cart cart, int productID, string returnUrl)//added Cart cart to bind
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductID == productID);
            if (product != null)
            {
                //GetCart().AddItem(product, 1);
               cart.AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)//added Cart cart to bind
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductID == productId);
            if (product != null)
            {
                //GetCart().RemoveLine(product);
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        //private Cart GetCart()
        //{
        //    Cart cart = (Cart)Session["Cart"];
        //    if(cart == null)
        //    {
        //        cart = new Cart();
        //        Session["Cart"] = cart; 
        //    }
        //    return cart;
        //}
        /*
         удалили метод GetCart и добавили параметр Cart cart в каждый метод действия. Когда MVC
  Framework получает запрос, который требует, скажем, вызвать метод AddToCart, она будет сначала
  смотреть на параметры для метода действия. Она рассмотрит список доступных механизмов
  связывания и попытается найти тот, который сможет создать экземпляры каждого типа параметра.
  Наш пользовательский механизм связывания должен будет создать объект Cart, что он и сделает,
  используя состояние сеанса. Между обращениями к нашему механизму связывания и механизму по
  умолчанию MVC Framework может создать набор параметров, которые необходимы для вызова
  метода действия, позволяя нам реорганизовать контроллер так, чтобы в нем не осталось сведений о
  том, как создаются объекты Cart при получении запросов.
           */

            //Partial for cart
        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if(cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }
            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }

        //For "Checkout now" Button
        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }
    }
}

ClimateStore.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClimateStore.Domain.Abstract;

namespace ClimateStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IProductRepository repository;

        public NavController(IProductRepository repo)
        {
            repository = repo;
        }
        public PartialViewResult Menu(string category =null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories = repository.Products
                .Select(x => x.Category)
                .Distinct()//Выборка по уникальным значениям
                .OrderBy(x => x);
            return PartialView(categories);
        }
        // GET: Nav
       // public string Menu()
       // {
       //     return "Hello from NavController";
       // }
    }
}
/*
конструктор, принимает реализацию IProductRepository как аргумент - после создания экземпляра контроллера ее предоставит Ninject, используя привязки.
***
Метод действия Menu, использует запрос LINQ, чтобы получить список категорий из хранилища и передать их в представление.
Так как в контроллере мы работаем с частичным представлением, мы вызываем метод PartialView, результатом является объект PartialViewResult.
 */

ClimateStore.WebUI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClimateStore.Domain.Abstract;
using ClimateStore.Domain.Entities;
using ClimateStore.WebUI.Models;

namespace ClimateStore.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository repository;
        public int PageSize = 4;                //указывает, что мы хотим видеть четыре товара на странице
        public ProductController(IProductRepository productRepository)
        {
            this.repository = productRepository;
        }

        public ViewResult List(string category,int page = 1)//add category
        {
            //объект ProductsListViewModel в качестве данных модели в представлени
            ProductsListViewModel model = new ProductsListViewModel
            {
                Products = repository.Products
                .Where(p => category == null || p.Category == category)// если category не содержит null, будут выбраны только те объекты Product, которые соответствуют свойству Category
                .OrderBy(p => p.ProductID)            //упорядочиваем их по первичному ключу
                .Skip((page - 1) * PageSize)         //пропускаем товары которые идут до начала нашей страницы
                .Take(PageSize),                    //берем количество товаров, указанное в поле PageSize
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    
                    //Если категория выбрана, возвращаем количество товаров в этой категории, если нет, возвращаем общее количество товаров.
                    TotalItems = category == null ?
                    repository.Products.Count() :
                    repository.Products.Where(e => e.Category == category).Count()
                },
                CurrentCategory = category //установили значение свойства CurrentCategory, добавленного в класс ProductsListViewModel
            };
            return View(model);
            //return View(repository.Products         //получаемобъекты Product из хранилища
            //    .OrderBy(p=>p.ProductID)            //упорядочиваем их по первичному ключу
            //    .Skip((page - 1)* PageSize)         //пропускаем товары которые идут до начала нашей страницы
            //    .Take(PageSize));                   //берем количество товаров, указанное в поле PageSize

        }

        public FileContentResult GetImage(int productId)
        {
            Product prod = repository.Products.FirstOrDefault(p => p.ProductID == productId);
            if (prod != null)
            {
                return File(prod.ImageData, prod.ImageMimeType);
            }
            else
            {
                return null;
            }
            /*
             метод пытается найти товар, который соответствует указанному в параметре ID.
            Он возвращает класс FileContentResult, когда мы хотим вернуть файл браузеру клиента,
            и экземпляры создаются с помощью метода File базового класса контроллера
             */
        }
    }
}

ClimateStore.WebUI/Views/Shared/ProductSummary.cshtml
@model ClimateStore.Domain.Entities.Product
<div class="item">
    @if (Model.ImageData != null) {
        <div style="float:left; margin-right: 20px">
            <img width="75" height="75" src="@Url.Action("GetImage", "Product", new { Model.ProductID})"/>
        </div>
    }
    <h3>@Model.Name</h3>
    @Model.Description
    <div class="item">
        @using (Html.BeginForm("AddToCart", "Cart"))
        {
            @Html.HiddenFor(x => x.ProductID)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" value="+ Add to cart" />
        }
    </div>
    <h4>@Model.Price.ToString("c")</h4>
</div>

ClimateStore.WebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/Admin.css" rel="stylesheet" type="text/css"/>
    <script src="~/Scripts/jquery-1.7.1.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @if (TempData["message"] != null) {
            <div class="Message">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

ClimateStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" type="text/css" rel="stylesheet" />
</head>
<body>
    <div id="header">
        @{Html.RenderAction("Summary", "Cart"); }
        <div class="title">CLIMATE STORE</div>
    </div>
    <div id="categories">
        @{Html.RenderAction("Menu", "Nav");} @*RenderAction записывает свое содержание непосредственно в поток ответа, как и метод
                                              RenderPartial. Это означает, что метод возвращает void, и поэтому его нельзя использовать
                                              с регулярным тегом Razor @. Вместо этого мы должны заключить вызов метода в блок кода Razor *@
    </div>
    <div id="content">
        @RenderBody()
    </div>
</body>
</html>